---
- name: Configure bastion host
  hosts: bastion
  become: yes

  tasks:
  - name: Install SSH server
    apt:
      name: openssh-server
      state: present

  - name: Configure SSH access
    template:
      src: templates/sshd_config.j2
      dest: /etc/ssh/sshd_config
    notify: restart ssh

  handlers:
  - name: restart ssh
    service:
      name: ssh
      state: restarted
