---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/alexander/.ssh/id_rsa
  children:
    bastion:
      hosts:
        bastion.ru-central1.internal:
    web_servers:
      hosts:
        web-instance-1.ru-central1.internal:
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@bastion.ru-central1.internal"
        web-instance-2.ru-central1.internal:
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@bastion.ru-central1.internal"
    zabbix:
      hosts:
        zabbix-server.ru-central1.internal:
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@bastion.ru-central1.internal"
    elasticsearch:
      hosts:
        elasticsearch-server.ru-central1.internal:
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@bastion.ru-central1.internal"
    kibana:
      hosts:
        kibana-server.ru-central1.internal:
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@bastion.ru-central1.internal"